### ISSUE TITLE
TypeError: call() got multiple values for argument 'names'

### ISSUE THREAD

**Issue by fepegar** [harvardnlp/namedtensor#84]
Hi, I'm trying to run the first lines in the README:
```python
from namedtensor import ntorch
x = ntorch.ones(10, 10, 20, names=("batch", "h", "w"))
```

But I'm getting this:
```python-traceback
TypeError                                 Traceback (most recent call last)
<ipython-input-2-6a1e9f556639> in <module>
----> 1 x = ntorch.ones(10, 10, 20, names=("batch", "h", "w"))

TypeError: call() got multiple values for argument 'names'
```

Have I missed anything?

**Comment by srush** [comment]
Hmm, this seems to work fine for me. Which python are you using and how did you install namedtensor?

**Comment by fepegar** [comment]
I just reproduced it with this script, `torchtest.sh`:
```shell
conda create -n torchtest -y
source activate torchtest
conda install pytorch torchvision -c pytorch -y
echo `which pip`
pip install namedtensor
python -c "from namedtensor import ntorch"  # complains about opt_einsum not installed
pip install opt-einsum
python -c "from namedtensor import ntorch; x = ntorch.ones(10, 10, 20, names=('batch', 'h', 'w'))"
```

And this is the output:
```shell
(miniconda3) ~/tmp  bash torchtest.sh                
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/fernando/miniconda3/envs/torchtest



Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate torchtest
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /Users/fernando/miniconda3/envs/torchtest

  added / updated specs:
    - pytorch
    - torchvision


The following NEW packages will be INSTALLED:

  blas               pkgs/main/osx-64::blas-1.0-mkl
  bzip2              conda-forge/osx-64::bzip2-1.0.6-h1de35cc_1002
  ca-certificates    conda-forge/osx-64::ca-certificates-2018.11.29-ha4d7672_0
  certifi            conda-forge/osx-64::certifi-2018.11.29-py37_1000
  cffi               conda-forge/osx-64::cffi-1.12.1-py37h342bebf_0
  freetype           conda-forge/osx-64::freetype-2.9.1-h597ad8a_1005
  intel-openmp       pkgs/main/osx-64::intel-openmp-2019.1-144
  jpeg               conda-forge/osx-64::jpeg-9c-h1de35cc_1001
  libcxx             conda-forge/osx-64::libcxx-7.0.0-h2d50403_2
  libffi             conda-forge/osx-64::libffi-3.2.1-h0a44026_1005
  libgfortran        conda-forge/osx-64::libgfortran-3.0.1-0
  libpng             conda-forge/osx-64::libpng-1.6.36-ha441bb4_1000
  libtiff            conda-forge/osx-64::libtiff-4.0.10-h79f4b77_1001
  llvm-meta          conda-forge/noarch::llvm-meta-7.0.0-0
  mkl                pkgs/main/osx-64::mkl-2019.1-144
  mkl_fft            conda-forge/osx-64::mkl_fft-1.0.10-py37h1de35cc_1
  mkl_random         conda-forge/osx-64::mkl_random-1.0.2-py37h1702cab_2
  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002
  ninja              conda-forge/osx-64::ninja-1.9.0-h04f5b5a_0
  numpy              pkgs/main/osx-64::numpy-1.15.4-py37hacdab7b_0
  numpy-base         pkgs/main/osx-64::numpy-base-1.15.4-py37h6575580_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openssl            conda-forge/osx-64::openssl-1.1.1a-h1de35cc_1000
  pillow             conda-forge/osx-64::pillow-5.4.1-py37hbddbef0_1000
  pip                conda-forge/osx-64::pip-19.0.3-py37_0
  pycparser          conda-forge/noarch::pycparser-2.19-py_0
  python             conda-forge/osx-64::python-3.7.1-hbdd33cc_1002
  pytorch            pytorch/osx-64::pytorch-1.0.1-py3.7_2
  readline           conda-forge/osx-64::readline-7.0-hcfe32e1_1001
  setuptools         conda-forge/osx-64::setuptools-40.8.0-py37_0
  six                conda-forge/osx-64::six-1.12.0-py37_1000
  sqlite             conda-forge/osx-64::sqlite-3.26.0-h1765d9f_1000
  tk                 conda-forge/osx-64::tk-8.6.9-ha441bb4_1000
  torchvision        pytorch/noarch::torchvision-0.2.1-py_2
  wheel              conda-forge/osx-64::wheel-0.33.1-py37_0
  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001
  zlib               conda-forge/osx-64::zlib-1.2.11-h1de35cc_1004


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
/Users/fernando/miniconda3/envs/torchtest/bin/pip
Collecting namedtensor
  Using cached https://files.pythonhosted.org/packages/74/8b/6ce953b8c6f105c86d5462cc78069c1980e7f1f5edded52faa0fc71e5a7e/namedtensor-0.0.2-py3-none-any.whl
Requirement already satisfied: numpy in /Users/fernando/miniconda3/envs/torchtest/lib/python3.7/site-packages (from namedtensor) (1.15.4)
Collecting einops (from namedtensor)
  Using cached https://files.pythonhosted.org/packages/36/1f/a5e6496a167b6e892123b201ccce251184457ce7a1b6c8e06662c09bfbab/einops-0.1.0-py3-none-any.whl
Installing collected packages: einops, namedtensor
Successfully installed einops-0.1.0 namedtensor-0.0.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/fernando/miniconda3/envs/torchtest/lib/python3.7/site-packages/namedtensor/__init__.py", line 2, in <module>
    from .torch_base import ntorch
  File "/Users/fernando/miniconda3/envs/torchtest/lib/python3.7/site-packages/namedtensor/torch_base.py", line 3, in <module>
    import opt_einsum as oe
ModuleNotFoundError: No module named 'opt_einsum'
Collecting opt-einsum
Requirement already satisfied: numpy>=1.7 in /Users/fernando/miniconda3/envs/torchtest/lib/python3.7/site-packages (from opt-einsum) (1.15.4)
Installing collected packages: opt-einsum
Successfully installed opt-einsum-2.3.2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: call() got multiple values for argument 'names'
```

As you see, there's a second issue: `opt-einsum` is not installed with `namedtensor`.

Let me know if you need any further info, I'm looking forward to using this package :)

**Comment by srush** [comment]
Oh sorry, I apologize for the delay. I need to update the pip package. 

For now use the development version. 

`!pip install -qU git+https://github.com/harvardnlp/namedtensor`

**Comment by fepegar** [comment]
Seems to work with the development version. Thanks!
